source /Users/mtunski/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-rupa-SLASH-z/z.sh
source /Users/mtunski/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-unixorn-SLASH-warhol.plugin.zsh/warhol.plugin.zsh
source /Users/mtunski/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-bric3-SLASH-nice-exit-code/nice-exit-code.plugin.zsh
source /Users/mtunski/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-caarlos0-SLASH-zsh-mkc/mkc.plugin.zsh
source /Users/mtunski/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-mtunski-SLASH-spaceship-prompt/spaceship.zsh
source /Users/mtunski/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source /Users/mtunski/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions/zsh-completions.plugin.zsh
source /Users/mtunski/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source /Users/mtunski/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-history-substring-search/zsh-history-substring-search.plugin.zsh
