SPACESHIP_PROMPT_ORDER=(
  user
  host
  dir
  git
  node
  ruby
  pyenv
  char
)

SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=false

SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_SYMBOL=">"

SPACESHIP_USER_SHOW="always"

SPACESHIP_NODE_PREFIX=""
SPACESHIP_NODE_SUFFIX=" "
SPACESHIP_NODE_SYMBOL="node-"
SPACESHIP_NODE_COLOR=0

SPACESHIP_RUBY_PREFIX=""
SPACESHIP_RUBY_SUFFIX=" "
SPACESHIP_RUBY_SYMBOL=""
SPACESHIP_RUBY_COLOR=0
