SPACESHIP_PROMPT_ORDER=(
  user
  host
  dir
  git
  node
  ruby
  elixir
  pyenv
  char
)

SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=false

SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_SYMBOL=">"

SPACESHIP_USER_SHOW="always"

SPACESHIP_NODE_PREFIX=""
SPACESHIP_NODE_SUFFIX=" "
SPACESHIP_NODE_SYMBOL="node-"
SPACESHIP_NODE_COLOR=8

SPACESHIP_RUBY_PREFIX=""
SPACESHIP_RUBY_SUFFIX=" "
SPACESHIP_RUBY_SYMBOL="ruby-"
SPACESHIP_RUBY_COLOR=8

SPACESHIP_ELIXIR_PREFIX=""
SPACESHIP_ELIXIR_SUFFIX=" "
SPACESHIP_ELIXIR_SYMBOL="elixir-"
SPACESHIP_ELIXIR_COLOR=8
