com.microsoft.VSCode public.text all
com.microsoft.VSCode public.xml all
com.microsoft.VSCode public.plain-text all
com.microsoft.VSCode public.script all
com.microsoft.VSCode public.shell-script all
com.microsoft.VSCode public.zsh-script all
com.microsoft.VSCode public.php-script all
com.microsoft.VSCode public.ruby-script all
com.microsoft.VSCode public.python-script all
com.microsoft.VSCode public.xhtml all
com.microsoft.VSCode public.json all
com.microsoft.VSCode public.comma-separated-values-text all
com.microsoft.VSCode public.swift-source all
com.microsoft.VSCode public.data all
